[metadata]
org = "example.com"
maintainer = "k8s-admin (me@example.com)"
description = "example Desired State File for demo purposes."
[certificates]

[settings]
kubeContext = "gke_praqma-education_europe-north1-a_helm-demo-telenor" # will try connect to this context first, if it does not exist, it will be created using the details below
serviceAccount = "tiller" # k8s serviceaccount must be already defined, validation error will be thrown otherwise
storageBackend = "secret" # default is configMap

[namespaces]
  [namespaces.production]
  protected = true
  [namespaces.development]
   protected = false
  [namespaces.kube-system]
   installTiller = false
   tillerServiceAccount = "tiller" 

[helmRepos]
stable = "https://kubernetes-charts.storage.googleapis.com"
incubator = "http://storage.googleapis.com/kubernetes-charts-incubator"

[apps]
    [apps.mysql]
    name = "mysql" # should be unique across all apps
    description = "mysql"
    namespace = "development" # maps to the namespace as defined in namespaces above
    enabled = true # change to false if you want to delete this app release [empty = false]
    chart = "stable/mysql" # changing the chart name means delete and recreate this chart
    version = "0.3.7" # chart version
    valuesFile = "applications/development/mysql-development-values.yaml" # leaving it empty uses the default chart values
    purge = false # will only be considered when there is a delete operation
    test = false # run the tests when this release is installed for the first time only
    protected = false
    priority= -3
    wait = true
    [apps.artifactory]
    name = "artifactory" # should be unique across all apps
    description = "artifactory"
    namespace = "production" # maps to the namespace as defined in namespaces above
    enabled = false # change to false if you want to delete this app release [empty = flase]
    chart = "stable/artifactory" # changing the chart name means delete and recreate this chart
    version = "7.0.6" # chart version
    valuesFile = "" # leaving it empty uses the default chart values
    purge = false # will only be considered when there is a delete operation
    test = false # run the tests when this release is installed for the first time only
    priority= -2
