version: 2
jobs:
  deploy-helm-charts:
    docker:
      - image: praqma/helmsman:v1.3.0-rc
    steps:
      - checkout
      - run: "mkdir ~/.kube ; echo $KUBECTL_CONFIG | base64 -d > ~/.kube/config"
      - run: "helmsman -debug -apply -f helmsman-deployments.toml"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-helm-charts
