version: 2
jobs:
  deploy-helm-charts:
    docker:
      # - image: praqma/helmsman:v1.3.0-rc
      # - image: praqma/helmsman:v1.2.0
      - image: kamranazeem/helmsman-fedora
    steps:
      # I will setup .kube/config using gcloud, before doing the checkout of the main demo repo.
      - run: echo ${GCLOUD_AUTH_FILE_JSON_BASE64} | base64 -d > ${HOME}/gcloud-auth-file.json
      - run: /google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=${HOME}/gcloud-auth-file.json
      - run: /google-cloud-sdk/bin/gcloud container clusters get-credentials ${GKE_CLUSTER_NAME} --zone ${GKE_CLUSTER_ZONE} --project ${GKE_CLUSTER_PROJECT_NAME}
      - run: ls -la ~/.kube
      - run: kubectl get nodes,pods
      - checkout
      - run: 
          name: deploy helm charts using helmsman
          command: helmsman -debug -apply -f helmsman-deployments.toml
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-helm-charts
